project:
  type: website
  output-dir: docs
  
website:
  title: "Genealogie"
  navbar:
    left:
      - text: "News"
        href: index.qmd
      - text: "Individus"
        href: page_individus.qmd
      - text: "Lieux"
        href: page_lieux.qmd
format:
  html:
    theme: minty
    toc: true
    toc-title: Sommaire
    number-sections: false
    echo: false
    embed-resources: true
    self-contained-math: true
    
pdf:
    echo: false
knitr:
  opts_chunk:
    out.width: "100%"