---
title: "News"
author: "Sarah Le Berre"
format: 
  html:
    theme: minty
    number-sections: false
    echo: false
    embed-resources: true
    self-contained-math: true
editor: visual
---

## 08.03.26 - Mise en ligne du site 

Le site est désormais en ligne ! 🎉\
Cette première version est loin d'être parfaite, mais elle permet déjà d’explorer notre arbre généalogique.

#### ✨ Nouveautés

**Arbre généalogique accessible**

-   Consultation des **dates de naissance, de mariage et de décès** de nos ancêtres jusqu’à **6 générations**.

-   Accès aux **noms de la 7ᵉ génération**.

**Navigation familiale**

-   Possibilité de parcourir les différentes branches de la famille avec le plan de page à droite et de remonter une lignée via le lien hypertexte sur les parents.

#### 🚧 En développement

**Page “Lieux”**

-   La section existe déjà mais est **encore vide pour le moment**. Elle sera enrichie plus tard avec pour présenter les lieux et lieux-dits dont sont originaires nos ancêtres avec des statistiques, anecdotes, etc.

#### 🔧 Notes

-   Le site vient tout juste d’être mis en ligne : certaines fonctionnalités pourront (et vont!) encore évoluer.

-   N’hésitez pas à signaler **erreurs, informations manquantes ou suggestions** pour améliorer l’arbre généalogique.

Merci à tous, j'espère que le site vous plaira !
